[package]
name = "rust"
version = "0.1.0"
edition = "2021"
autolib = false
autobins = false
autoexamples = false
autotests = false
autobenches = false

[dependencies]

[[bin]]
name = "aoc"
path = "./src/main/rust/main.rs"
